services:
  db:
    image: postgres:17
    container_name: db_app
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}

#  redis:
#    image: redis:7
#    container_name: redis_app
#    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Ex
#    expose:
#      - ${REDIS_PORT}

  app:
    build:
      context: .
    container_name: fastapi_app
    command: [ "/app/docker/app.sh" ]
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db