services:
  db:
    image: postgres:17
    container_name: db_app
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}

#  redis:
#    image: redis:7
#    container_name: redis_app
#    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --notify-keyspace-events Ex
#    expose:
#      - ${REDIS_PORT}

  app:
    build:
      context: .
    container_name: fastapi_app
    command: [ "/app/docker/app.sh" ]
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - HTTP_PROXY=socks5://172.17.0.1:10808  # IP хоста Docker (обычно gateway) и порт V2Ray
      - HTTPS_PROXY=socks5://172.17.0.1:10808
      - ALL_PROXY=socks5://172.17.0.1:10808
      - NO_PROXY="bot,db,localhost,127.0.0.1,172.17.0.0/16"
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db

  bot:
    build:
      context: .
    container_name: bot
    command: ["python", "./src/main_bot.py"]
    depends_on:
      - app