CREATE_SYSTEM_PROMPT_TEMPLATE = """YOUR TEMPLATE HERE"""
CREATE_RANDOM_PROMPT = """YOUR_PROMPT_HERE"""
CREATE_NAME_TEMPLATE = """YOUR_PROMPT_HERE"""

GERALT_PROMPT = """A"""
PICKME_PROMPT = """B"""
NEKO_PROMPT = """C"""
SMART_PROMPT = """D"""